### PR TITLE
Hinge Pin

### PR DESCRIPTION
**Pull request by tabashir**
Hi.
I tweaked the code to allow you to choose whether you use the existing sphere based hinge or whether to just make a hole through so that you can use a screw, bolt or bit of 3d Filament as your hinge fixing.
I've found his makes it a little stronger.
There is also the option of not hulling the base and lid, so it is more of a forked cross / tricorn instead of looking like a hexagon.

### CODE REVIEW

**Comment by moucha19** [comment]
Hi!

this is a very good idea and I would like to merge it. But first, it would be great if you could do these small fixes if possible:
* Revert the modifications of the presets. You can add newly introduced parameter but set it so that the rendered model stays the same. 
* Change back `hinge_pin_diameter` to `hinge_pin`
* Remove hulled_base as a top parameter - use hull base with the default hinge, and the standard cross with the holes.
* Add the new `hinge_holes` parameter to README

**Comment by tabashir** [comment]
Hi.

Happy to revert the presets and change the README.

I do have a few questions on the other parts though.

I changed hinge_pin to hinge_pin_diameter because that more accurately reflects what it is that is being changed. A parameter called hinge_pin sounds more like a boolean yes/no, so calling it diameter made it easier to see what is going on, particularly when changing the code. Is there a particular reason this needs to change back? 

Regarding the hulled_base top parameter, what you suggest is actually what I originally coded. However, when using the cross based version, I found that easier to hold and fletch with, even when using the original hinge types, so I changed it to allow the user to choose which they preferred regardless of hinge.  We could default each one, so the cross is with the holes and the hulled is with the spheres, but change the variable to be called base_style_override which forces the style if it is set, but uses the defaults if not?

What do you think?

**Comment by moucha19** [comment]
Hi again!

I try to keep names of top level parameters shown in the customizer as simple and short as possible. The context is provided in a customizer as a comment and the data type is also obvious there. If the pin wouldn't be a spherical shape with only one relevant parameter, I would agree that that the name lacks a context, but here it's not a case.

When it comes to the cross base, I think you got a point  and I like using *style* in the parameter 😸 You can maybe change  `hinge_holes` to `hinge_style` to control if ball joints or holes are used and `base_style` to select cross/hexagon or the default option based on the `hinge_style`. Would this be okay with you? Also, don't worry about README, because I realized that these parameters are not referenced in the current drawings. I work on reworking all the drawings in FreeCAD, so I will add these parameters after all that is done.

Thanks a lot!

**Comment by tabashir** [comment]
Hi. Sorry for delay in replying. No worries, will get on it.

**Comment by tabashir** [comment]
That should all be done in the updated branch now. Let me know if there is anything else you need doing.

**Comment by tabashir** [comment]
Happy to sort any conflicts, but wasn't sure what branch you really wanted this PR pointed at.

**Comment by moucha19** [comment]
Closing because I merge your other pull request without conflicts. Cheers!

**Pull request closed without merging**
